### ISSUE TITLE
Ego filtering should not assume 'id' prop

### ISSUE THREAD

**Issue by bryfox** [codaco/networkQuery#3]
The [egoRule assumes that network nodes will have an 'id' property equal to 1](https://github.com/codaco/networkQuery/blob/master/query.js#L90). A node will never have this property set.

Based on https://github.com/codaco/Network-Canvas/issues/583, we might want to look for a documented `isEgo` property in a nodes' `attributes` property. See also https://github.com/codaco/Network-Canvas/issues/584.

**Comment by bryfox** [comment]
The egoRule also [defines egoNode as an array, but assumes it's a node object](https://github.com/codaco/networkQuery/blob/master/query.js#L90-L91).

Both of these issues will be solved if we [model ego separately](https://github.com/codaco/Network-Canvas/issues/584#issuecomment-433961619).

**Comment by jthrilly** [comment]
Let's go with modelling Ego separately.

**Comment by wwqrd** [comment]
Resolved by https://github.com/codaco/networkQuery/pull/9
